### ISSUE TITLE
[FEAT] 데이터 정제

### ISSUE THREAD

**Issue by EunHee-Jeong** [EunHee-Jeong/Open-Source-Project#1]
## 📌  Feature Issue

데이터 정제하기

## 📝  To-do

- [x] 데이터 불러오기 & 확인하기
- [x] 202번 버스의 평균 승하차 인원 추출하기
- [x] 노선별 평균 승하차 인원 추출하기
- [x] 시각화해서 비교하기
